server:
  servlet:
    context-path: /issue-tracker
  error:
    include-exception: true
  port: 8000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock
  datasource:
    url: jdbc:mysql://localhost:3307/issue-tracker
    username: root
    password: root

logging:
  level:
    com.it: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    org.liquibase: INFO
    org.springframework.boot: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger

jwt:
  secret: zSUjJmmMbDy9N7y9xqVJrwDDr5MSu4JF3rmN9xKcupCHnJ6yD
